version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/frontend
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev
    ports:
      - "7777:7777"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app/backend
    depends_on:
      - mongodb
