version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-prod
    image: hmohammed2/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-prod
    image: hmohammed2/backend:latest
    ports:
      - "7777:7777"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - NODE_ENV=production
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}